### ISSUE TITLE
Replace deprecated functions in active_directory lib

### ISSUE THREAD

**Issue by Kvel2D** [altlinuxteam/adtool#34]

**Comment by NIR-Ginko** [comment]
Which functions are deprecated?

**Comment by Kvel2D** [comment]
LDAP lib lets you know what is deprecated by giving an implicit declaration warning.
> warning: implicit declaration of function ‘ldap_value_free’; did you mean ‘ldap_value_free_len’? [-Wimplicit-function-declaration]
So any functions that give this warning.

**Comment by NIR-Ginko** [comment]
I'll take it.

**Comment by NIR-Ginko** [comment]
Related to https://github.com/altlinuxteam/adtool/pull/38

**Comment by NIR-Ginko** [comment]
https://github.com/altlinuxteam/adtool/pull/42
